server:
  port: 9191

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=PersonalProjectsDB
    username: sa
    password: pass@123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

