spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=TestDB
    username: sa
    password: H@r$ha@123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

